name: ecmwf_forecasts
channels:
  - conda-forge
dependencies:
  - python=3.12.11
  - numpy=2.3.2
  - xarray=2025.9.0
  - rasterio=1.4.3
  - ecmwf-opendata=0.3.23
  - cfgrib=0.9.15.0
  - netcdf4=1.7.2
  - jupyter=1.1.1